name: ci 
on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: mkdir ~/docs
      - run: mv * ~/docs
      - run: mv ~/docs .
      - run: git clone https://github.com/karpovilia/mkdocs_template.git
      - run: rm -rf mkdocs_template/.git/
      - run: rm -rf mkdocs_template/docs/
      - run: mv mkdocs_template/* .
      - run: rm -rf mkdocs_template/
      - run: 'echo "site_name: Social Network Analysis Magolego 2022" >> mkdocs.yml'
      - run: cat /home/runner/work/hsesna2022/hsesna2022/mkdocs.yml
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
